spring.application.name=TaskManager

spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=default
spring.datasource.password=



spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#create-drop: (Default for embedded databases like H2) Creates the schema when the
#application starts and drops it when the application stops.