package com.cagritasoz.taskmanager.infrastructure.adapter.outbound.database.entity;

import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;


/* ======================================
           @Entity EXPLANATION
   ======================================
  1.@Entity is part of JPA. It tells JPA (the Java Persistence API) that this class is a persistent entity. Meaning
  Instances of this class can be stored in a database and managed by the JPA entity manager.

  2.Without @Entity, JPA ignores this class; it won't persist objects.
  3.A no-argument constructor is required for JPA to instantiate entities via reflection.
  4.Entities are automatically managed by JPA (can be persisted, merged, removed, or detached).
 */
@Entity

/* ======================================
           @Table EXPLANATION
   ======================================
  1. @Table(name = "users") overrides the default table name (class name). If omitted, the table name defaults to "UserEntity".
 */
@Table(name = "users")
public class UserEntity {

/* ======================================
            PRIMARY KEY MAPPING
   ======================================
  1.@Id marks the primary key field of an entity. @GeneratedValue is a JPA annotation used in combination with @Id

  2.@GeneratedValue indicates that the primary key is auto-generated by the database.
  -@GeneratedValue can take two parameters strategy(Defines how the ID is generated)
  -generator(Refers to the name of a custom generator (used with @SequenceGenerator or @TableGenerator))
  -strategy = GenerationType.IDENTITY → database auto-increments the ID.
  -strategy = GenerationType.AUTO → JPA chooses the strategy based on database dialect.
  -strategy = GenerationType.SEQUENCE → can define a sequence generator (good for Oracle/PostgreSQL).

  3. Every entity MUST have a primary key; it is used by JPA to track entity identity.
 */
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

/* ======================================
            FIELD/COLUMN MAPPING
   ======================================
  1.@Column maps a Java field to a database column.

  2. Parameters:
  - name: column name in DB
  - nullable: whether NULL is allowed (default = true)
  - unique: whether the column has a unique constraint (default = false)
  - length: maximum length for Strings (applies to VARCHAR)

  3.Column definitions affect database schema generation if using Hibernate DDL.
  4.Avoid storing sensitive data in plain text (password should be hashed before persisting).
 */
    @Column(name = "username", nullable = false, length = 50)
    private String username;

    @Column(name = "email", nullable = false, unique = true)
    private String email;

    @Column(name = "password", nullable = false)
    private String password;

/* =========================================
        RELATIONSHIPS / ASSOCIATIONS
   =========================================
  @OneToMany annotation indicates a one-to-many relationship. When used on a field it means that side is the "one" side.
  @ManyToOne annotation indicates a many-to-one relationship. When used on a field it means that side is the "many" side.

  -For bidirectional mapping to be achieved user has to know about their tasks and task has to know about its user.
  -Bidirectional mapping allows navigation both ways: User → Tasks, Task → User.

  -A user can have multiple tasks but a task can only belong to one user. UserEntity -> One side, TaskEntity -> Many side.
  -The “one side” or “many side” refers to the entity as a whole, not a specific field.
  -This means that user has to have the field List<TaskEntity> tasks, task has to have the field UserEntity user.
  -In a bidirectional sense the one side (UserEntity) typically has a List or Set of the many-side entity (TaskEntity).
   and the many side (TaskEntity) has a single object reference to the one-side entity (UserEntity). This is the standard.

  -For a proper bidirectional relationship, since both entities should know about each other, we use @OneToMany annotation
   on UserEntity.task and @ManyToOne annotation on TaskEntity.user

  -Terms parent/child side and inverse/owner side are introduced. Owner side(TaskEntity) has the foreign key.
  -The foreign key is determined with @JoinColumn(name = "user_id"). Foreign key now has the name "user_id".
  -@JoinColumn is used on the owner side which is TaskEntity.
  -A foreign key is a column (or a set of columns) in one table that references the primary key of another table.

  -Inverse side is determined by mappedBy = "user". This tells JPA that the inverse side is UserEntity.
  -The value is the name of the owner-side field.
  -mappedBy attribute is used on the inverse side(UserEntity).
  -Tells JPA “look at this field on the other entity -> that side owns the FK”.

  -To properly set up a bidirectional mapping, we both have use @JoinColumn and mappedBy to avoid confusions and clarity.
  -It is best practise to use them for clarity and no unpredictability, do not avoid them.

  =========================================
            FETCHING STRATEGY
  =========================================
  -Fetch means to load data from the database into memory (i.e., converting rows into entity objects)
  -Fetch types can be specified as attributes in the @OneToMany or @ManyToOne annotations.

  - fetch = FetchType.LAZY (default for OneToMany) → tasks are loaded only when accessed (user.getTasks()).
  (Avoids potential unnecessary memory load)

  - fetch = FetchType.EAGER (default for ManyToOne) → tasks loaded immediately (usually discouraged for large collections).
  (Ensures parent entity is loaded with child if used on the "one" side)

  -Accessing a lazy collection triggers a separate SQL query.
  -Use JOIN FETCH in queries if you want to load collections efficiently in a single query.
  -Beware of N+1 query problem when fetching collections in loops.

   ========================================
                  CASCADING
   ========================================
  -CascadeType defines which operations propagate from parent to child entities.
  -Common types: ALL, PERSIST, MERGE, REMOVE, REFRESH, DETACH.

  -Examples:
  1. CascadeType.ALL → operations on User propagate to Tasks (persist, merge, remove etc.)
  2.Cascading is almost always defined on the parent/inverse side.

  -orphanRemoval = true, is an attribute we can add to @OneToMany or @OneToOne relationships.
  -It tells JPA:
  -“If a child entity is removed from the parent’s collection (or unlinked from the parent)
   automatically delete it from the database.”
 */
    @OneToMany(mappedBy = "user", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private final List<TaskEntity> tasks = new ArrayList<>();

    public UserEntity() {}

    public UserEntity(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<TaskEntity> getTasks() {
        return tasks;
    }

    public void addTask(TaskEntity task) {
        tasks.add(task);
        task.setUser(this); //Very important to also set the user field of the task when adding a task.
    }

    public void removeTask(TaskEntity task) {
        tasks.remove(task); //Automatically triggers orphan removal.
    }
}
